apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basketball-film-review.fullname" . }}-backend
  labels:
    {{- include "basketball-film-review.labels" . | nindent 4 }}
    component: backend
