{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    component: postgres
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.app.name }}-onepassword
    kind: SecretStore
  target:
    name: {{ .Values.app.name }}-postgres-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-credentials
        property: password
    - secretKey: database
      remoteRef:
        key: postgres-credentials
        property: database
{{- end }}
