{{- if and .Values.externalSecrets.enabled .Values.cloudflared.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-cloudflare-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    component: cloudflared
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.app.name }}-onepassword
    kind: SecretStore
  target:
    name: {{ .Values.app.name }}-cloudflared-credentials
    creationPolicy: Owner
    template:
      data:
        credentials.json: |
          {
            "AccountTag": "{{ `{{ .accountId }}` }}",
            "TunnelSecret": "{{ `{{ .tunnelSecret }}` }}",
            "TunnelID": "{{ `{{ .tunnelId }}` }}"
          }
  data:
    - secretKey: accountId
      remoteRef:
        key: cloudflare-tunnel
        property: account-id
    - secretKey: tunnelId
      remoteRef:
        key: cloudflare-tunnel
        property: tunnel-id
    - secretKey: tunnelSecret
      remoteRef:
        key: cloudflare-tunnel
        property: tunnel-secret
{{- end }}
