{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
    component: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.app.name }}-onepassword
    kind: SecretStore
  target:
    name: {{ .Values.app.name }}-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: rootUser
      remoteRef:
        key: minio-credentials
        property: username
    - secretKey: rootPassword
      remoteRef:
        key: minio-credentials
        property: password
{{- end }}
