{{- if .Values.analysisOperator.enabled }}
{{- if .Values.analysisOperator.googleApiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: google-api-key
  labels:
    {{- include "basketball-film-review.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.analysisOperator.googleApiKey | quote }}
{{- end }}
{{- end }}
