{{- if .Values.analysisOperator.enabled }}
{{- if .Values.analysisOperator.replicateApiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: replicate-api-token
  labels:
    {{- include "basketball-film-review.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.analysisOperator.replicateApiToken | quote }}
{{- end }}
{{- end }}
