apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  username: {{ .Values.secrets.postgres.username | quote }}
  password: {{ .Values.secrets.postgres.password | quote }}
  database: {{ .Values.secrets.postgres.database | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  labels:
    app: {{ .Values.app.name }}
type: Opaque
stringData:
  rootUser: {{ .Values.secrets.minio.rootUser | quote }}
  rootPassword: {{ .Values.secrets.minio.rootPassword | quote }}
