{{- if .Values.externalSecrets.enabled -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.app.name }}-onepassword
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  provider:
    onepassword:
      connectHost: {{ .Values.externalSecrets.onepassword.connectHost }}
      vaults:
        k8s: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: {{ .Values.externalSecrets.onepassword.tokenSecretName }}
            key: token
{{- end }}
