apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: app-eng-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.18.0.50-172.18.0.55
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: app-eng-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - app-eng-pool
