apiVersion: v2
name: basketball-film-review
description: A Helm chart for Basketball Film Review application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  
  - name: minio
    version: "5.0.15"
    repository: "https://charts.min.io/"
    condition: minio.enabled
